// <auto-generated />
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(_DBContext))]
    partial class _DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Database.Definitions.CatalogData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Код");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Cpu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Процессор");

                    b.Property<bool>("Flag_Del")
                        .HasColumnType("bit")
                        .HasComment("Флаг удалено");

                    b.Property<string>("FpsBarWidth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("FPS прогресс");

                    b.Property<string>("FpsModalSerialized")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Сериализованное FPS модальное окно");

                    b.Property<string>("FpsNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("FPS На главной");

                    b.Property<string>("Gpu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Графическая карта");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Имя продукта");

                    b.Property<bool>("IsHit")
                        .HasColumnType("bit")
                        .HasComment("IsHit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Имя продукта");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Стоимость");

                    b.Property<string>("Ram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Оперативка");

                    b.Property<string>("SpecsModalSerialized")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Сериализованное модальное окно");

                    b.Property<string>("StatusClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Статус");

                    b.Property<string>("StatusText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Текст статуса");

                    b.HasKey("ID");

                    b.ToTable("CatalogDatas", t =>
                        {
                            t.HasComment("Продукты каталога");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
